[package]
name = "mobilenet-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["wgpu", "train", "vision"] }
image = "0.25.5"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.216", features = ["derive"] }
ndarray = "0.16.1"

[dev-dependencies]
